#!/usr/bin/env python
# Siwanont Sittinam
# Recognition Control

# Import necessary modules
import optparse as optparse
import sys as sys

from lib.predict_dataset import PredictonWeb, PredictonLine

def whenError(parser):
    parser.print_help()
    sys.exit(1)

def main():
    parse = optparse.OptionParser("Usage: %prog run [options]")
    parse.add_option('-s', '--show', default=False, action="store_true" , help="start web server to show camera", dest="show")
    options, arguments = parse.parse_args()
    if arguments and arguments[0].lower() == "run":
        if options.show:
            PredictonWeb().run()
        else:
            PredictonLine().run()
    else:
        whenError(parse)

if __name__ == '__main__':
    main()
